import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        {/* Background layers */}
        <div className="fixed inset-0 -z-20 bg-gradient-to-br from-pink-200 via-orange-100 to-green-200" />
        <div className="fixed inset-0 -z-10 bg-gradient-to-tr from-purple-200 via-pink-100 to-blue-200 opacity-70 blur-3xl" />

        {/* App content */}
        <div className="relative z-10">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
